# -*- coding: utf-8 -*-
"""HW2_hash_practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ehGxR5W06un0K9kwsAFO3tcmWKNAvqX4
"""

#import data
from google.colab import drive
drive.mount('/content/drive')
path='/content/drive/MyDrive/Colab Notebooks/hw2_data.txt'
data_list=[]

#turn list into dict
def Convert(data_list):
  res_dict={}
  for i in range(0,len(data_list),2):
    res_dict[data_list[i]]=data_list[i+1]
  return res_dict

#turn txt into list and add number for calculation
with open(path,'r') as f:
  data=f.readlines()
  for word in data:
    data=word.replace("\n","")
    data_list.append(data)
    data_list.append("1")

#calculate the number of types of food
line="總共有"+str(len(Convert(data_list)))+"種英文字"
print(line)

# remove number in list
for i in range(0,len(data_list),2):
    data_list.remove("1")

#calculate the amount of food
def Count(data_list):
  data_dict={}
  for i in range(0,len(data_list)):
    if data_list[i] not in data_dict:
      data_dict[data_list[i]]=1
    else:
      data_dict[data_list[i]]+=1
  return data_dict

print(Count(data_list))